# Generated by Django 5.1.3 on 2024-11-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.DateField(verbose_name='Vigencia')),
                ('plazo', models.PositiveIntegerField(verbose_name='Plazo (días)')),
                ('vencimiento', models.DateField(verbose_name='Vencimiento')),
                ('tipo_poliza', models.CharField(choices=[('BUEN USO DEL ANTICIPO', 'Buen Uso del Anticipo'), ('OTRO TIPO', 'Otro Tipo')], max_length=50, verbose_name='Tipo de Póliza')),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Asegurado')),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('prima_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima Mínima')),
                ('prima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prima')),
                ('derecho', models.DecimalField(decimal_places=2, default=3.0, max_digits=10, verbose_name='Derecho')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotizador',
                'verbose_name_plural': 'Cotizadores',
                'db_table': 'cotizador',
                'ordering': ['id'],
            },
        ),
    ]
